server:
 port: 8080
 servlet:
  context-path: /films
spring:
 application: 
  name: filmsServer
mybatis-plus:
 typeAliasesPackage: com.appdemos.films.entity
 global-config:
  id-type: 0
  field-strategy: 0
  db-column-underline: true
  refresh-mapper: true
    #capital-mode: true
 configuration:
  map-underscore-to-camel-case: true
  cache-enabled: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

