server:
 port: 7070
spring:
 application:
  name: spring-cloud-configServer
 cloud:
  config:
   server:
    git:
     uri: https://github.com/superDSB/spring-cloud-config.git
     force-pull: true
     username: superDSB
     password: Lys10086
management:
 endpoints:
  web:
   exposure:
    include: "*"
 security:
  enabled: false
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:7080/eureka